# Generated by Django 3.2.16 on 2023-01-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-quantity',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
